### ISSUE TITLE
ACF Gallery doesn't work

### ISSUE THREAD

**Issue by Caspert** [bearded-avenger/fotos#4]
Hi Bearded Advenger,

I downloaded your plugin. Install the plugin ACF Gallery. Create a new gallery field with the plugin. No problems. But when I add images to them, and save the post, all images disappears that I have added before uploading.

Do you know what the problem could be? Have you maybe an update for this plugin?

Look out for your answer

**Comment by bearded-avenger** [comment]
I don't work with pagelines any longer and do not provide support for this.
